FROM node:12 as build-stage
WORKDIR /app
COPY /template .
RUN yarn cache clean
RUN yarn install
RUN yarn build

FROM nginx as production-stage
RUN mkdir -p /app/app
COPY --from=build-stage /app/build /app/app
COPY /template/nginx.conf /etc/nginx/nginx.conf